In [1]:
import pandas as pd

# Base Acidente

In [2]:
df_crash = pd.read_csv('datasets/crash.csv', low_memory=False)

In [3]:
df_crash.shape

(1069048, 49)

In [4]:
df_crash.info()

<class 'pandas.DataFrame'>
RangeIndex: 1069048 entries, 0 to 1069047
Data columns (total 49 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   CRASH_RECORD_ID                1069048 non-null  str
 1   CRASH_DATE_EST_I               77289 non-null    str
 2   CRASH_DATE                     1069048 non-null  str
 3   POSTED_SPEED_LIMIT             1069048 non-null  int64
 4   TRAFFIC_CONTROL_DEVICE         1069048 non-null  str
 5   DEVICE_CONDITION               1069048 non-null  str
 6   WEATHER_CONDITION              1069048 non-null  str
 7   LIGHTING_CONDITION             1069048 non-null  str
 8   FIRST_CRASH_TYPE               1069048 non-null  str
 9   TRAFFICWAY_TYPE                1069048 non-null  str
 10  LANE_CNT                       199044 non-null   str
 11  ALIGNMENT                      1069048 non-null  str
 12  ROADWAY_SURFACE_COND           1069048 non-null  str
 13  ROAD_DEFECT                    1069048 non-null  str
 14  REPORT_TYPE                    1032880 non-null  str
 15  CRASH_TYPE                     1069048 non-null  str
 16  INTERSECTION_RELATED_I         245568 non-null   str
 17  NOT_RIGHT_OF_WAY_I             47651 non-null    str
 18  HIT_AND_RUN_I                  335543 non-null   str
 19  DAMAGE                         1069048 non-null  str
 20  DATE_POLICE_NOTIFIED           1069048 non-null  str
 21  PRIM_CONTRIBUTORY_CAUSE        1069048 non-null  str
 22  SEC_CONTRIBUTORY_CAUSE         1069048 non-null  str
 23  STREET_NO                      1069048 non-null  int64
 24  STREET_DIRECTION               1069044 non-null  str
 25  STREET_NAME                    1069047 non-null  str
 26  BEAT_OF_OCCURRENCE             1069043 non-null  float64
 27  PHOTOS_TAKEN_I                 15474 non-null    str
 28  STATEMENTS_TAKEN_I             25911 non-null    str
 29  DOORING_I                      3402 non-null     str
 30  WORK_ZONE_I                    5735 non-null     str
 31  WORK_ZONE_TYPE                 4357 non-null     str
 32  WORKERS_PRESENT_I              1469 non-null     str
 33  NUM_UNITS                      1069048 non-null  int64
 34  CRASH_MONTH                    1069048 non-null  int64
 35  MOST_SEVERE_INJURY             1066725 non-null  str
 36  INJURIES_TOTAL                 1066740 non-null  float64
 37  INJURIES_FATAL                 1066740 non-null  float64
 38  INJURIES_INCAPACITATING        1066740 non-null  float64
 39  INJURIES_NON_INCAPACITATING    1066740 non-null  float64
 40  INJURIES_REPORTED_NOT_EVIDENT  1066740 non-null  float64
 41  INJURIES_NO_INDICATION         1066740 non-null  float64
 42  INJURIES_UNKNOWN               1066740 non-null  float64
 43  CRASH_HOUR                     1069048 non-null  int64
 44  CRASH_DAY_OF_WEEK              1069048 non-null  int64
 45  IDOT_CONTROL_NO                1066242 non-null  str
 46  LATITUDE                       1060779 non-null  float64
 47  LONGITUDE                      1060779 non-null  float64
 48  LOCATION                       1060779 non-null  str
dtypes: float64(10), int64(6), str(33)
memory usage: 399.7 MB

In [5]:
info_colunas = pd.DataFrame({
    "coluna": df_crash.columns,
    "tipo": df_crash.dtypes.astype(str),
    "qtd_nao_nulos": df_crash.notna().sum().values,
    "qtd_nulos": df_crash.isna().sum().values,
    "perc_nulos": (df_crash.isna().mean().values * 100).round(2),
    "qtd_valores_unicos": df_crash.nunique(dropna=True).values
})

info_colunas

,coluna,tipo,qtd_nao_nulos,qtd_nulos,perc_nulos,qtd_valores_unicos
CRASH_RECORD_ID,CRASH_RECORD_ID,str,1069048,0,0.00,1069048
CRASH_DATE_EST_I,CRASH_DATE_EST_I,str,77289,991759,92.77,2
CRASH_DATE,CRASH_DATE,str,1069048,0,0.00,708374
POSTED_SPEED_LIMIT,POSTED_SPEED_LIMIT,int64,1069048,0,0.00,47
TRAFFIC_CONTROL_DEVICE,TRAFFIC_CONTROL_DEVICE,str,1069048,0,0.00,19
DEVICE_CONDITION,DEVICE_CONDITION,str,1069048,0,0.00,8
WEATHER_CONDITION,WEATHER_CONDITION,str,1069048,0,0.00,12
LIGHTING_CONDITION,LIGHTING_CONDITION,str,1069048,0,0.00,6
FIRST_CRASH_TYPE,FIRST_CRASH_TYPE,str,1069048,0,0.00,18
TRAFFICWAY_TYPE,TRAFFICWAY_TYPE,str,1069048,0,0.00,20
LANE_CNT,LANE_CNT,str,199044,870004,81.38,41
ALIGNMENT,ALIGNMENT,str,1069048,0,0.00,6
ROADWAY_SURFACE_COND,ROADWAY_SURFACE_COND,str,1069048,0,0.00,7
ROAD_DEFECT,ROAD_DEFECT,str,1069048,0,0.00,7
REPORT_TYPE,REPORT_TYPE,str,1032880,36168,3.38,3
CRASH_TYPE,CRASH_TYPE,str,1069048,0,0.00,2
INTERSECTION_RELATED_I,INTERSECTION_RELATED_I,str,245568,823480,77.03,2
NOT_RIGHT_OF_WAY_I,NOT_RIGHT_OF_WAY_I,str,47651,1021397,95.54,2
HIT_AND_RUN_I,HIT_AND_RUN_I,str,335543,733505,68.61,2
DAMAGE,DAMAGE,str,1069048,0,0.00,3
DATE_POLICE_NOTIFIED,DATE_POLICE_NOTIFIED,str,1069048,0,0.00,809071
PRIM_CONTRIBUTORY_CAUSE,PRIM_CONTRIBUTORY_CAUSE,str,1069048,0,0.00,40
SEC_CONTRIBUTORY_CAUSE,SEC_CONTRIBUTORY_CAUSE,str,1069048,0,0.00,40
STREET_NO,STREET_NO,int64,1069048,0,0.00,12034
STREET_DIRECTION,STREET_DIRECTION,str,1069044,4,0.00,4
STREET_NAME,STREET_NAME,str,1069047,1,0.00,1676
BEAT_OF_OCCURRENCE,BEAT_OF_OCCURRENCE,float64,1069043,5,0.00,277
PHOTOS_TAKEN_I,PHOTOS_TAKEN_I,str,15474,1053574,98.55,2
STATEMENTS_TAKEN_I,STATEMENTS_TAKEN_I,str,25911,1043137,97.58,2
DOORING_I,DOORING_I,str,3402,1065646,99.68,2
WORK_ZONE_I,WORK_ZONE_I,str,5735,1063313,99.46,2
WORK_ZONE_TYPE,WORK_ZONE_TYPE,str,4357,1064691,99.59,4
WORKERS_PRESENT_I,WORKERS_PRESENT_I,str,1469,1067579,99.86,2
NUM_UNITS,NUM_UNITS,int64,1069048,0,0.00,17
CRASH_MONTH,CRASH_MONTH,int64,1069048,0,0.00,12
MOST_SEVERE_INJURY,MOST_SEVERE_INJURY,str,1066725,2323,0.22,5
INJURIES_TOTAL,INJURIES_TOTAL,float64,1066740,2308,0.22,21
INJURIES_FATAL,INJURIES_FATAL,float64,1066740,2308,0.22,5
INJURIES_INCAPACITATING,INJURIES_INCAPACITATING,float64,1066740,2308,0.22,10
INJURIES_NON_INCAPACITATING,INJURIES_NON_INCAPACITATING,float64,1066740,2308,0.22,20
INJURIES_REPORTED_NOT_EVIDENT,INJURIES_REPORTED_NOT_EVIDENT,float64,1066740,2308,0.22,14
INJURIES_NO_INDICATION,INJURIES_NO_INDICATION,float64,1066740,2308,0.22,51
INJURIES_UNKNOWN,INJURIES_UNKNOWN,float64,1066740,2308,0.22,1
CRASH_HOUR,CRASH_HOUR,int64,1069048,0,0.00,24
CRASH_DAY_OF_WEEK,CRASH_DAY_OF_WEEK,int64,1069048,0,0.00,7
IDOT_CONTROL_NO,IDOT_CONTROL_NO,str,1066242,2806,0.26,1066205
LATITUDE,LATITUDE,float64,1060779,8269,0.77,355931
LONGITUDE,LONGITUDE,float64,1060779,8269,0.77,355927
LOCATION,LOCATION,str,1060779,8269,0.77,355961

In [6]:
colunas_numericas = df_crash.select_dtypes(include=["int64", "float64"]).columns.tolist()
colunas_categoricas = df_crash.select_dtypes(include=["str"]).columns.tolist()

print("Quantidade de colunas numéricas:", len(colunas_numericas))
print("Quantidade de colunas categóricas:", len(colunas_categoricas))

Quantidade de colunas numéricas: 16
Quantidade de colunas categóricas: 33

In [7]:
colunas_numericas

['POSTED_SPEED_LIMIT',
 'STREET_NO',
 'BEAT_OF_OCCURRENCE',
 'NUM_UNITS',
 'CRASH_MONTH',
 'INJURIES_TOTAL',
 'INJURIES_FATAL',
 'INJURIES_INCAPACITATING',
 'INJURIES_NON_INCAPACITATING',
 'INJURIES_REPORTED_NOT_EVIDENT',
 'INJURIES_NO_INDICATION',
 'INJURIES_UNKNOWN',
 'CRASH_HOUR',
 'CRASH_DAY_OF_WEEK',
 'LATITUDE',
 'LONGITUDE']

In [12]:
colunas_categoricas

['CRASH_RECORD_ID',
 'CRASH_DATE_EST_I',
 'CRASH_DATE',
 'TRAFFIC_CONTROL_DEVICE',
 'DEVICE_CONDITION',
 'WEATHER_CONDITION',
 'LIGHTING_CONDITION',
 'FIRST_CRASH_TYPE',
 'TRAFFICWAY_TYPE',
 'LANE_CNT',
 'ALIGNMENT',
 'ROADWAY_SURFACE_COND',
 'ROAD_DEFECT',
 'REPORT_TYPE',
 'CRASH_TYPE',
 'INTERSECTION_RELATED_I',
 'NOT_RIGHT_OF_WAY_I',
 'HIT_AND_RUN_I',
 'DAMAGE',
 'DATE_POLICE_NOTIFIED',
 'PRIM_CONTRIBUTORY_CAUSE',
 'SEC_CONTRIBUTORY_CAUSE',
 'STREET_DIRECTION',
 'STREET_NAME',
 'PHOTOS_TAKEN_I',
 'STATEMENTS_TAKEN_I',
 'DOORING_I',
 'WORK_ZONE_I',
 'WORK_ZONE_TYPE',
 'WORKERS_PRESENT_I',
 'MOST_SEVERE_INJURY',
 'IDOT_CONTROL_NO',
 'LOCATION']

In [8]:
def plot_null_values(df):
    nulos = df.isna().sum().reset_index()
    nulos.columns = ["coluna", "qtd_nulos"]

    nulos["perc_nulos"] = (nulos["qtd_nulos"] / len(df) * 100).round(2)

    nulos = nulos.sort_values("perc_nulos", ascending=False)

    return nulos
plot_null_values(df_crash)

                           coluna  qtd_nulos  perc_nulos
32              WORKERS_PRESENT_I    1067579       99.86
29                      DOORING_I    1065646       99.68
31                 WORK_ZONE_TYPE    1064691       99.59
30                    WORK_ZONE_I    1063313       99.46
27                 PHOTOS_TAKEN_I    1053574       98.55
28             STATEMENTS_TAKEN_I    1043137       97.58
17             NOT_RIGHT_OF_WAY_I    1021397       95.54
1                CRASH_DATE_EST_I     991759       92.77
10                       LANE_CNT     870004       81.38
16         INTERSECTION_RELATED_I     823480       77.03
18                  HIT_AND_RUN_I     733505       68.61
14                    REPORT_TYPE      36168        3.38
46                       LATITUDE       8269        0.77
47                      LONGITUDE       8269        0.77
48                       LOCATION       8269        0.77
45                IDOT_CONTROL_NO       2806        0.26
37                 INJURIES_FATAL       2308        0.22
42               INJURIES_UNKNOWN       2308        0.22
41         INJURIES_NO_INDICATION       2308        0.22
40  INJURIES_REPORTED_NOT_EVIDENT       2308        0.22
39    INJURIES_NON_INCAPACITATING       2308        0.22
35             MOST_SEVERE_INJURY       2323        0.22
38        INJURIES_INCAPACITATING       2308        0.22
36                 INJURIES_TOTAL       2308        0.22
9                 TRAFFICWAY_TYPE          0        0.00
4          TRAFFIC_CONTROL_DEVICE          0        0.00
3              POSTED_SPEED_LIMIT          0        0.00
2                      CRASH_DATE          0        0.00
5                DEVICE_CONDITION          0        0.00
0                 CRASH_RECORD_ID          0        0.00
6               WEATHER_CONDITION          0        0.00
7              LIGHTING_CONDITION          0        0.00
8                FIRST_CRASH_TYPE          0        0.00
15                     CRASH_TYPE          0        0.00
13                    ROAD_DEFECT          0        0.00
11                      ALIGNMENT          0        0.00
12           ROADWAY_SURFACE_COND          0        0.00
21        PRIM_CONTRIBUTORY_CAUSE          0        0.00
22         SEC_CONTRIBUTORY_CAUSE          0        0.00
23                      STREET_NO          0        0.00
24               STREET_DIRECTION          4        0.00
26             BEAT_OF_OCCURRENCE          5        0.00
25                    STREET_NAME          1        0.00
19                         DAMAGE          0        0.00
20           DATE_POLICE_NOTIFIED          0        0.00
34                    CRASH_MONTH          0        0.00
33                      NUM_UNITS          0        0.00
44              CRASH_DAY_OF_WEEK          0        0.00
43                     CRASH_HOUR          0        0.00

In [9]:
limite_nulos = 0.50

# Calcula a proporção de valores nulos por coluna
percentual_nulos = df_crash.isnull().mean()

# Seleciona colunas com mais de 50% de valores nulos
cols_to_drop = percentual_nulos[percentual_nulos > limite_nulos].index

# Remove as colunas
df_crash = df_crash.drop(columns=cols_to_drop)

# Visualiza novamente
plot_null_values(df_crash)

                           coluna  qtd_nulos  perc_nulos
12                    REPORT_TYPE      36168        3.38
36                      LONGITUDE       8269        0.77
37                       LOCATION       8269        0.77
35                       LATITUDE       8269        0.77
34                IDOT_CONTROL_NO       2806        0.26
27        INJURIES_INCAPACITATING       2308        0.22
26                 INJURIES_FATAL       2308        0.22
29  INJURIES_REPORTED_NOT_EVIDENT       2308        0.22
30         INJURIES_NO_INDICATION       2308        0.22
31               INJURIES_UNKNOWN       2308        0.22
28    INJURIES_NON_INCAPACITATING       2308        0.22
25                 INJURIES_TOTAL       2308        0.22
24             MOST_SEVERE_INJURY       2323        0.22
0                 CRASH_RECORD_ID          0        0.00
5               WEATHER_CONDITION          0        0.00
4                DEVICE_CONDITION          0        0.00
3          TRAFFIC_CONTROL_DEVICE          0        0.00
2              POSTED_SPEED_LIMIT          0        0.00
1                      CRASH_DATE          0        0.00
6              LIGHTING_CONDITION          0        0.00
8                 TRAFFICWAY_TYPE          0        0.00
7                FIRST_CRASH_TYPE          0        0.00
21             BEAT_OF_OCCURRENCE          5        0.00
20                    STREET_NAME          1        0.00
19               STREET_DIRECTION          4        0.00
18                      STREET_NO          0        0.00
17         SEC_CONTRIBUTORY_CAUSE          0        0.00
16        PRIM_CONTRIBUTORY_CAUSE          0        0.00
15           DATE_POLICE_NOTIFIED          0        0.00
14                         DAMAGE          0        0.00
13                     CRASH_TYPE          0        0.00
11                    ROAD_DEFECT          0        0.00
10           ROADWAY_SURFACE_COND          0        0.00
9                       ALIGNMENT          0        0.00
23                    CRASH_MONTH          0        0.00
22                      NUM_UNITS          0        0.00
33              CRASH_DAY_OF_WEEK          0        0.00
32                     CRASH_HOUR          0        0.00

In [10]:
df_crash = df_crash.dropna()
plot_null_values(df_crash)

                           coluna  qtd_nulos  perc_nulos
0                 CRASH_RECORD_ID          0         0.0
1                      CRASH_DATE          0         0.0
2              POSTED_SPEED_LIMIT          0         0.0
3          TRAFFIC_CONTROL_DEVICE          0         0.0
4                DEVICE_CONDITION          0         0.0
5               WEATHER_CONDITION          0         0.0
6              LIGHTING_CONDITION          0         0.0
7                FIRST_CRASH_TYPE          0         0.0
8                 TRAFFICWAY_TYPE          0         0.0
9                       ALIGNMENT          0         0.0
10           ROADWAY_SURFACE_COND          0         0.0
11                    ROAD_DEFECT          0         0.0
12                    REPORT_TYPE          0         0.0
13                     CRASH_TYPE          0         0.0
14                         DAMAGE          0         0.0
15           DATE_POLICE_NOTIFIED          0         0.0
16        PRIM_CONTRIBUTORY_CAUSE          0         0.0
17         SEC_CONTRIBUTORY_CAUSE          0         0.0
18                      STREET_NO          0         0.0
19               STREET_DIRECTION          0         0.0
20                    STREET_NAME          0         0.0
21             BEAT_OF_OCCURRENCE          0         0.0
22                      NUM_UNITS          0         0.0
23                    CRASH_MONTH          0         0.0
24             MOST_SEVERE_INJURY          0         0.0
25                 INJURIES_TOTAL          0         0.0
26                 INJURIES_FATAL          0         0.0
27        INJURIES_INCAPACITATING          0         0.0
28    INJURIES_NON_INCAPACITATING          0         0.0
29  INJURIES_REPORTED_NOT_EVIDENT          0         0.0
30         INJURIES_NO_INDICATION          0         0.0
31               INJURIES_UNKNOWN          0         0.0
32                     CRASH_HOUR          0         0.0
33              CRASH_DAY_OF_WEEK          0         0.0
34                IDOT_CONTROL_NO          0         0.0
35                       LATITUDE          0         0.0
36                      LONGITUDE          0         0.0
37                       LOCATION          0         0.0

## Duplicatas

In [11]:
duplicadas = df_crash.duplicated().sum()

print("Quantidade de linhas duplicadas:", duplicadas)
print("Percentual de linhas duplicadas:", round(duplicadas / len(df_crash) * 100, 2))

Quantidade de linhas duplicadas: 0
Percentual de linhas duplicadas: 0.0